In [ ]:
!git --version

git version 2.43.0

In [ ]:
!git clone https://github.com/somyathakur0101-cmd/CareFlow-Clinical-Pathway-Process-Mining.git

Cloning into 'CareFlow-Clinical-Pathway-Process-Mining'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.

In [ ]:
%cd /content/CareFlow-Clinical-Pathway-Process-Mining

/content/CareFlow-Clinical-Pathway-Process-Mining

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [ ]:
!git branch
!git remote -v

* main
origin	https://github.com/somyathakur0101-cmd/CareFlow-Clinical-Pathway-Process-Mining.git (fetch)
origin	https://github.com/somyathakur0101-cmd/CareFlow-Clinical-Pathway-Process-Mining.git (push)

In [ ]:
!ls -la

total 16
drwxr-xr-x 3 root root 4096 Oct 12 15:33 .
drwxr-xr-x 1 root root 4096 Oct 12 15:33 ..
drwxr-xr-x 8 root root 4096 Oct 12 15:35 .git
-rw-r--r-- 1 root root  113 Oct 12 15:33 README.md

In [ ]:
!git switch -c giri-charan

Switched to a new branch 'giri-charan'

In [ ]:
!git branch

* giri-charan
  main

In [ ]:
!cat README.md

# CareFlow-Clinical-Pathway-Process-Mining
Clinical pathway process mining and healthcare data analysis project.

In [ ]:

import pandas as pd
from google.colab import files

uploaded = files.upload()

filename = next(iter(uploaded))

df = pd.read_csv(filename)

print("DATASET LOADED SUCCESSFULLY")
print("-" * 50)

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nFIRST FIVE RECORDS")
display(df.head())

print("\nCOLUMN NAMES")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

print("\nDATA TYPES")
print(df.dtypes)

schema = pd.DataFrame({
    "Column_Name": df.columns,
    "Data_Type": [str(df[col].dtype) for col in df.columns],
    "Non_Missing_Count": df.notna().sum().values,
    "Missing_Count": df.isna().sum().values,
    "Missing_Percentage": (
        df.isna().mean().values * 100
    ).round(2)
})

print("\nDATASET SCHEMA REPORT")
display(schema)

print("\nDATA TYPE SUMMARY")
print(df.dtypes.value_counts())

datetime_columns = [
    col for col in df.columns
    if "datetime" in col.lower()
    or "date" in col.lower()
    or "time" in col.lower()
]

print("\nCOLUMNS THAT MAY CONTAIN DATES/TIMES")
for col in datetime_columns:
    print(f"{col}: current type = {df[col].dtype}")

empty_columns = df.columns[df.isna().all()].tolist()

print("\nCOMPLETELY EMPTY COLUMNS")
if empty_columns:
    print(empty_columns)
else:
    print("No completely empty columns found.")

print("\nNUMERICAL COLUMN SUMMARY")
display(df.describe())

schema.to_csv("CareFlow_Dataset_Schema.csv", index=False)

print("\nSchema report saved successfully.")

files.download("CareFlow_Dataset_Schema.csv")

Saving HospitalOPD-noname (1) (1).csv to HospitalOPD-noname (1) (1).csv
DATASET LOADED SUCCESSFULLY
--------------------------------------------------
Number of rows: 62422
Number of columns: 25

FIRST FIVE RECORDS

,record_no,patient_id,Unnamed: 2,appointment_id,appointment_start_datetime,prescription_doctor_id,prescription_doctor_name,prescription_order_id,prescription_start_datetime,prescription_end_datetime,...,imaging_result_id,imaging_name,imaging_start_datetime,imaging_end_datetime,pharmacy_sale_line_id,medicine_name,pharmacy_start_datetime,pharmacy_end_datetime,flow_code,flow_name
0,1,10,NaN,445911,3/30/2026 5:36,225,Admin,106357,3/30/2026 5:38,3/30/2026 6:48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
1,2,57,NaN,335085,10/14/2025 5:23,193,Dr. Abrar Ahmed Bhatti,43515,10/14/2025 5:39,10/14/2025 5:53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
2,3,57,NaN,335085,10/14/2025 5:23,193,Dr. Abrar Ahmed Bhatti,43541,10/14/2025 6:11,10/14/2025 6:24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
3,4,60,NaN,322358,9/25/2025 13:36,195,Dr. Anique Ahmed,34654,9/25/2025 13:50,9/25/2025 13:51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
4,5,72,NaN,337714,10/17/2025 6:40,202,Dr. Mehreen Batool Bokhari,45263,10/17/2025 6:49,10/17/2025 6:49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription

COLUMN NAMES
1. record_no
2. patient_id
3. Unnamed: 2
4. appointment_id
5. appointment_start_datetime
6. prescription_doctor_id
7. prescription_doctor_name
8. prescription_order_id
9. prescription_start_datetime
10. prescription_end_datetime
11. lab_id
12. lab_name
13. lab_start_datetime
14. lab_end_datetime
15. imaging_request_id
16. imaging_result_id
17. imaging_name
18. imaging_start_datetime
19. imaging_end_datetime
20. pharmacy_sale_line_id
21. medicine_name
22. pharmacy_start_datetime
23. pharmacy_end_datetime
24. flow_code
25. flow_name

DATA TYPES
record_no                        int64
patient_id                       int64
Unnamed: 2                     float64
appointment_id                   int64
appointment_start_datetime      object
prescription_doctor_id           int64
prescription_doctor_name        object
prescription_order_id            int64
prescription_start_datetime     object
prescription_end_datetime       object
lab_id                         float64
lab_name                        object
lab_start_datetime              object
lab_end_datetime                object
imaging_request_id             float64
imaging_result_id              float64
imaging_name                    object
imaging_start_datetime          object
imaging_end_datetime            object
pharmacy_sale_line_id          float64
medicine_name                   object
pharmacy_start_datetime         object
pharmacy_end_datetime           object
flow_code                        int64
flow_name                       object
dtype: object

DATASET SCHEMA REPORT

,Column_Name,Data_Type,Non_Missing_Count,Missing_Count,Missing_Percentage
0,record_no,int64,62422,0,0.00
1,patient_id,int64,62422,0,0.00
2,Unnamed: 2,float64,0,62422,100.00
3,appointment_id,int64,62422,0,0.00
4,appointment_start_datetime,object,62422,0,0.00
5,prescription_doctor_id,int64,62422,0,0.00
6,prescription_doctor_name,object,62422,0,0.00
7,prescription_order_id,int64,62422,0,0.00
8,prescription_start_datetime,object,62410,12,0.02
9,prescription_end_datetime,object,62421,1,0.00
10,lab_id,float64,18029,44393,71.12
11,lab_name,object,18029,44393,71.12
12,lab_start_datetime,object,18029,44393,71.12
13,lab_end_datetime,object,18029,44393,71.12
14,imaging_request_id,float64,5523,56899,91.15
15,imaging_result_id,float64,5523,56899,91.15
16,imaging_name,object,5523,56899,91.15
17,imaging_start_datetime,object,5523,56899,91.15
18,imaging_end_datetime,object,5513,56909,91.17
19,pharmacy_sale_line_id,float64,302,62120,99.52
20,medicine_name,object,302,62120,99.52
21,pharmacy_start_datetime,object,302,62120,99.52
22,pharmacy_end_datetime,object,302,62120,99.52
23,flow_code,int64,62422,0,0.00
24,flow_name,object,62422,0,0.00

DATA TYPE SUMMARY
object     14
int64       6
float64     5
Name: count, dtype: int64

COLUMNS THAT MAY CONTAIN DATES/TIMES
appointment_start_datetime: current type = object
prescription_start_datetime: current type = object
prescription_end_datetime: current type = object
lab_start_datetime: current type = object
lab_end_datetime: current type = object
imaging_start_datetime: current type = object
imaging_end_datetime: current type = object
pharmacy_start_datetime: current type = object
pharmacy_end_datetime: current type = object

COMPLETELY EMPTY COLUMNS
['Unnamed: 2']

NUMERICAL COLUMN SUMMARY

,record_no,patient_id,Unnamed: 2,appointment_id,prescription_doctor_id,prescription_order_id,lab_id,imaging_request_id,imaging_result_id,pharmacy_sale_line_id,flow_code
count,62422.000000,62422.000000,0.0,62422.000000,62422.000000,62422.000000,18029.000000,5523.000000,5523.000000,3.020000e+02,62422.000000
mean,31211.500000,197813.482827,NaN,365161.770978,301.059835,61300.726170,162479.041932,58815.842658,46132.510230,1.027663e+06,1.505863
std,18019.823589,92588.439085,NaN,50125.852538,144.546867,27840.389402,42757.075477,7990.213899,6186.563136,2.287418e+05,0.844461
min,1.000000,10.000000,NaN,317.000000,156.000000,10.000000,827.000000,34731.000000,26754.000000,5.857770e+05,1.000000
25%,15606.250000,120614.000000,NaN,326837.000000,181.000000,37699.250000,132866.000000,53102.500000,41856.000000,1.009620e+06,1.000000
50%,31211.500000,240149.000000,NaN,364410.500000,221.000000,60625.000000,163990.000000,58610.000000,46057.000000,1.070450e+06,1.000000
75%,46816.750000,270600.000000,NaN,408331.000000,390.000000,86143.500000,198735.000000,65348.500000,50984.500000,1.146100e+06,2.000000
max,62422.000000,308365.000000,NaN,452095.000000,615.000000,109572.000000,232318.000000,74336.000000,58330.000000,1.798480e+06,7.000000

Schema report saved successfully.

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:

import pandas as pd
from google.colab import files

schema = pd.DataFrame({
    "Column_Name": df.columns,
    "Data_Type": [str(df[col].dtype) for col in df.columns],
    "Non_Missing_Count": df.notna().sum().values,
    "Missing_Count": df.isna().sum().values,
    "Missing_Percentage": (df.isna().mean().values * 100).round(2)
})

schema.to_csv("CareFlow_Dataset_Schema.csv", index=False)

print("Schema report created successfully!")
print("Total columns:", len(schema))
display(schema)

files.download("CareFlow_Dataset_Schema.csv")

Schema report created successfully!
Total columns: 25

,Column_Name,Data_Type,Non_Missing_Count,Missing_Count,Missing_Percentage
0,record_no,int64,62422,0,0.00
1,patient_id,int64,62422,0,0.00
2,Unnamed: 2,float64,0,62422,100.00
3,appointment_id,int64,62422,0,0.00
4,appointment_start_datetime,object,62422,0,0.00
5,prescription_doctor_id,int64,62422,0,0.00
6,prescription_doctor_name,object,62422,0,0.00
7,prescription_order_id,int64,62422,0,0.00
8,prescription_start_datetime,object,62410,12,0.02
9,prescription_end_datetime,object,62421,1,0.00
10,lab_id,float64,18029,44393,71.12
11,lab_name,object,18029,44393,71.12
12,lab_start_datetime,object,18029,44393,71.12
13,lab_end_datetime,object,18029,44393,71.12
14,imaging_request_id,float64,5523,56899,91.15
15,imaging_result_id,float64,5523,56899,91.15
16,imaging_name,object,5523,56899,91.15
17,imaging_start_datetime,object,5523,56899,91.15
18,imaging_end_datetime,object,5513,56909,91.17
19,pharmacy_sale_line_id,float64,302,62120,99.52
20,medicine_name,object,302,62120,99.52
21,pharmacy_start_datetime,object,302,62120,99.52
22,pharmacy_end_datetime,object,302,62120,99.52
23,flow_code,int64,62422,0,0.00
24,flow_name,object,62422,0,0.00

In [ ]:
%cd /content/CareFlow-Clinical-Pathway-Process-Mining

!git status
!git branch
!ls -la

[Errno 2] No such file or directory: '/content/CareFlow-Clinical-Pathway-Process-Mining'
/content
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
total 10088
drwxr-xr-x 1 root root     4096 Oct 13 15:54  .
drwxr-xr-x 1 root root     4096 Oct 13 15:50  ..
-rw-r--r-- 1 root root     1062 Oct 13 16:05  CareFlow_Dataset_Schema.csv
drwxr-xr-x 4 root root     4096 Oct  2 13:50  .config
-rw-r--r-- 1 root root 10306961 Oct 13 15:54 'HospitalOPD-noname (1) (1).csv'
drwxr-xr-x 1 root root     4096 Oct  2 13:50  sample_data

In [ ]:
%cd /content

!git clone https://github.com/somyathakur0101-cmd/CareFlow-Clinical-Pathway-Process-Mining.git

/content
Cloning into 'CareFlow-Clinical-Pathway-Process-Mining'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.

In [ ]:
%cd /content/CareFlow-Clinical-Pathway-Process-Mining

!git status
!git branch
!git remote -v
!ls -la

/content/CareFlow-Clinical-Pathway-Process-Mining
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
* main
origin	https://github.com/somyathakur0101-cmd/CareFlow-Clinical-Pathway-Process-Mining.git (fetch)
origin	https://github.com/somyathakur0101-cmd/CareFlow-Clinical-Pathway-Process-Mining.git (push)
total 16
drwxr-xr-x 3 root root 4096 Oct 13 16:36 .
drwxr-xr-x 1 root root 4096 Oct 13 16:36 ..
drwxr-xr-x 8 root root 4096 Oct 13 16:37 .git
-rw-r--r-- 1 root root  113 Oct 13 16:36 README.md

In [ ]:
%cd /content/CareFlow-Clinical-Pathway-Process-Mining

!git switch -c giri-charan

/content/CareFlow-Clinical-Pathway-Process-Mining
Switched to a new branch 'giri-charan'

In [ ]:
from google.colab import files
files.download("CareFlow_Dataset_Schema.csv")

FileNotFoundError: Cannot find file: CareFlow_Dataset_Schema.csv


##  Missing Values Analysis

**Objective:** To identify missing values in each column of the original HospitalOPD dataset and calculate their missing percentages.

In [ ]:

import pandas as pd
from google.colab import files
from io import BytesIO

uploaded = files.upload()
filename = next(iter(uploaded))

df = pd.read_csv(BytesIO(uploaded[filename]))

print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

Saving HospitalOPD-noname (1).csv to HospitalOPD-noname (1).csv
Total Rows: 62422
Total Columns: 25

In [ ]:

df.isnull().sum()

record_no                          0
patient_id                         0
Unnamed: 2                     62422
appointment_id                     0
appointment_start_datetime         0
prescription_doctor_id             0
prescription_doctor_name           0
prescription_order_id              0
prescription_start_datetime       12
prescription_end_datetime          1
lab_id                         44393
lab_name                       44393
lab_start_datetime             44393
lab_end_datetime               44393
imaging_request_id             56899
imaging_result_id              56899
imaging_name                   56899
imaging_start_datetime         56899
imaging_end_datetime           56909
pharmacy_sale_line_id          62120
medicine_name                  62120
pharmacy_start_datetime        62120
pharmacy_end_datetime          62120
flow_code                          0
flow_name                          0
dtype: int64

In [ ]:

(df.isnull().mean() * 100).round(2)

record_no                        0.00
patient_id                       0.00
Unnamed: 2                     100.00
appointment_id                   0.00
appointment_start_datetime       0.00
prescription_doctor_id           0.00
prescription_doctor_name         0.00
prescription_order_id            0.00
prescription_start_datetime      0.02
prescription_end_datetime        0.00
lab_id                          71.12
lab_name                        71.12
lab_start_datetime              71.12
lab_end_datetime                71.12
imaging_request_id              91.15
imaging_result_id               91.15
imaging_name                    91.15
imaging_start_datetime          91.15
imaging_end_datetime            91.17
pharmacy_sale_line_id           99.52
medicine_name                   99.52
pharmacy_start_datetime         99.52
pharmacy_end_datetime           99.52
flow_code                        0.00
flow_name                        0.00
dtype: float64

In [ ]:

missing_report = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percentage (%)': (df.isnull().mean() * 100).round(2)
})

display(missing_report)

                             Missing Count  Missing Percentage (%)
record_no                                0                    0.00
patient_id                               0                    0.00
Unnamed: 2                           62422                  100.00
appointment_id                           0                    0.00
appointment_start_datetime               0                    0.00
prescription_doctor_id                   0                    0.00
prescription_doctor_name                 0                    0.00
prescription_order_id                    0                    0.00
prescription_start_datetime             12                    0.02
prescription_end_datetime                1                    0.00
lab_id                               44393                   71.12
lab_name                             44393                   71.12
lab_start_datetime                   44393                   71.12
lab_end_datetime                     44393                   71.12
imaging_request_id                   56899                   91.15
imaging_result_id                    56899                   91.15
imaging_name                         56899                   91.15
imaging_start_datetime               56899                   91.15
imaging_end_datetime                 56909                   91.17
pharmacy_sale_line_id                62120                   99.52
medicine_name                        62120                   99.52
pharmacy_start_datetime              62120                   99.52
pharmacy_end_datetime                62120                   99.52
flow_code                                0                    0.00
flow_name                                0                    0.00

In [ ]:
missing_report.to_csv('Member2_Missing_Values_Report.csv')
files.download('Member2_Missing_Values_Report.csv')

### Findings – Missing Values Analysis

- Total rows: 62,422
- Total columns: 25
- `Unnamed: 2` has 100% missing values.
- Lab-related columns have approximately 71.12% missing values.
- Imaging-related columns have approximately 91.15%–91.17% missing values.
- Pharmacy-related columns have approximately 99.52% missing values.
- Most appointment and prescription columns have no missing values or very few missing values.